version: "3.8"

services:
  db:
    image: postgres:15
    container_name: edu
    environment:
      POSTGRES_PASSWORD: "edu"
      POSTGRES_USER: "edu"
      POSTGRES_DB: "edu"
    volumes:
      - edu:/var/lib/postregsql/data
    ports:
      - 5432:5432

volumes:
  edu:
